using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TheBlogProject.Models;

namespace MarkdownMvc.Models
{
    public class PostRepo
    {
        public static List<Post> GetPosts()
        {
            List<Post> PostList = new(){
                //new Post(){
                //    Title = "First post",
                //    Abstract = "Define the underlying",
                //    Content = "Define the underlying principles that drive decisions and strategy for your design language bleeding edge onward and upward"
                //    // The above text was generated by Office Ipsum http://officeipsum.com/index.php
                //},
                //new Post(){
                //    Title = "Second post",
                //    Abstract = "so what's our",
                //    Content = "so what's our go to market strategy?. Customer centric all hands on deck yet where the metal hits the meat define"
                //},
                //new Post(){
                //    Title = "Not visible",
                //    Abstract = "not important",
                //    Content = "not important, you should not see this post"
                //},
                //new Post(){
                //    Title = "Third post",
                //    Abstract = "the underlying",
                //    Content = "the underlying principles that drive decisions and strategy for your design language not the long pole",
                //},
                //new Post(){
                //    Title = "Fourth post",                   
                //    Abstract = "in the future",
                //    Content = "Post scheduling made super easy",
                //    DateCreated = DateTime.Now.AddDays(3) // Post scheduling made easy
                //},
                 new Post(){
                    Title = "Markdown Test",
                    Abstract = "Let's see what markdown can do",
                    Content =   "# Hello world\n"+
                                "**Lorem** ipsum dolor sit"+
                                "amet, *consectetur* adipiscing elit. Sed"+
                                "eu est nec metus luctus tempus. Pellentesque"+
                                "at elementum sapien, ac faucibus sem"+
                                "![surprise](https://media.giphy.com/media/fdyZ3qI0GVZC0/giphy.gif)"
                }
            };
            return PostList;
        }

    }
}
